# extract_agents.py
import base64, zipfile, io, os

b64 = """UEsDBAoAAAAAAMFqUVkAAAAAAAAAAAAAAAAIAAAAYWdlbnRzL1BLAwQKAAAAAADBalFZAAAAAAAA
AAAAAAAABAAAAGFnZW50cy9fX2luaXRfXy5weQBLAwQKAAAAAADBalFZAAAAAAAAAAAAAAAAFQAA
AGFnZW50cy9iYXNlLnB5UEsDBAoAAAAAAMFqUVkAAAAAAAAAAAAAAAATAAAAYWdlbnRzL2FyY2hp
dGVjdF9hZ2VudC5weQBLAwQKAAAAAADBalFZAAAAAAAAAAAAAAAAEQAAAGFnZW50cy9jb2Rlcl9h
Z2VudC5weQBLAwQKAAAAAADBalFZAAAAAAAAAAAAAAAAEQAAAGFnZW50cy9jcml0aWNfYWdlbnQu
cHlQSwMECgAAAAAAwWpRWQAAAAAAAAAAAAAAAA8AAABhZ2VudHMvZGVidWdfYWdlbnQucHlQSwME
CgAAAAAAwWpRWQAAAAAAAAAAAAAAAA8AAABhZ2VudHMvcmVzZWFyY2hlcl9hZ2VudC5weVBLAwQK
AAAAAADBalFZAAAAAAAAAAAAAAAAEQAAAGFnZW50cy9zdXBlcnZpc29yX2FnZW50LnB5UEsDBAoA
AAAAAMFqUVkAAAAAAAAAAAAAAAARAAAAYWdlbnRzL3Rlc3Rlcl9hZ2VudC5weVBLAwQKAAAAAADB
alFZAAAAAAAAAAAAAAAAFQAAAGFnZW50cy9yZXF1aXJlbWVudHMudHh0UEsDBAoAAAAAAMFqUVkA
AAAAAAAAAAAAAAARAAAAYWdlbnRzL1JFQURNRS5tZFBQSwECFAAKAAAAAADBalFZAAAAAAAAAAAA
AAAACAAAAAAAAAAgAAAAAAAAAABhZ2VudHMvUEsBAhQACgAAAAAAwWpRWQAAAAAAAAAAAAAAAAQA
AAAAAAAAIAAAAAAAAAABhZ2VudHMvX19pbml0X18ucHlQSwECFAAKAAAAAADBalFZAAAAAAAA
AAAAAAAVAAAAAAAAACAAAAAAAAAAAGFnZW50cy9iYXNlLnB5UEsBAhQACgAAAAAAwWpRWQAA
AAAAAAATAAAAAAAAACAAAAAAAAAAAGFnZW50cy9hcmNoaXRlY3RfYWdlbnQucHlQSwECFAAK
AAAAAADBalFZAAAAAAAAAAAAAAAAEQAAAAAAAAAgAAAAAAAAAABhZ2VudHMvY29kZXJfYWdlbnQu
cHlQSwECFAAKAAAAAADBalFZAAAAAAAAAAAAAAAAEQAAAAAAAAAgAAAAAAAAAABhZ2VudHMvY3Jp
dGljX2FnZW50LnB5UEsBAhQACgAAAAAAwWpRWQAAAAAAAAAAAAAAAA8AAAAAAAAAIAAAAAAAAAAA
YWdlbnRzL2RlYnVnX2FnZW50LnB5UEsBAhQACgAAAAAAwWpRWQAAAAAAAAAAAAAAAA8AAAAAAAAA
IAAAAAAAAAABhZ2VudHMvcmVzZWFyY2hlcl9hZ2VudC5weVBLAwQKAAAAAADBalFZAAAAAAAA
AAAAAAAAEQAAAAAAAAAgAAAAAAAAAABhZ2VudHMvc3VwZXJ2aXNvcl9hZ2VudC5weVBLAwQK
AAAAAADBalFZAAAAAAAAAAAAAAAAEQAAAAAAAAAgAAAAAAAAAABhZ2VudHMvdGVzdGVyX2FnZW50
LnB5UEsBAhQACgAAAAAAwWpRWQAAAAAAAAAAAAAAAAUAAAAAAAAAIAAAAAAAAAABhZ2VudHMv
cmVxdWlyZW1lbnRzLnR4dFBLAQIUAAoAAAAAAMFqUVkAAAAAAAAAAAAAAAARAAAAAAAAACAA
AAAAAAAAAGFnZW50cy9SRUFETUUubWRQSwUGAAAAAAkACQB7AQAAqAcAAAAA"""

# Padding düzeltme
missing_padding = len(b64) % 4
if missing_padding:
    b64 += "=" * (4 - missing_padding)

zip_bytes = base64.b64decode(b64)

# Bellekte aç ve diske çıkar
with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
    zf.extractall(".")

print("✅ agents/ klasörü başarıyla oluşturuldu!")
# Klasör içeriğini listele
for root, dirs, files in os.walk("agents"):
    level = root.replace("agents", "").count(os.sep)
    indent = " " * 2 * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = " " * 2 * (level + 1)
    for file in files:
        print(f"{subindent}{file}")